# version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:5000  # Point frontend to the backend container
    networks:
      - app-network
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend
          target: /src
          action: rebuild

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "6379:6379"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
  redis:
    image: "redis:alpine"
networks:
  app-network:
    driver: bridge

volumes:
  backend:
